---
title: "ShinyLabView"
output: 
  flexdashboard::flex_dashboard:
    #theme: sandstone
    #vertical_layout: scroll
    navbar:
      - { icon: "fa-github", 
          title: "Source-Code",
          href: "https://github.com/s1lvester/shinyLabView", 
          align: right }
runtime: shiny
---

```{r global, include=FALSE}
library(dplyr)
library(lubridate)
library(DT)
library(scales)
library(ggplot2)
library(plotly)
library(htmltools)

labData <- read.csv("./labData-Tests-norm.csv") # loading data in global needs to be done only once.
patData <- read.csv2("./patientData.csv")
normValues <- read.csv2("./normValues.csv")
combinedData <- merge(labData, patData, by = "patientId")

# build normValue-Column Data for main Datatable
femaleNormValues <- data.frame(normValues$parameter, normValues$female.min, normValues$female.max)
names(femaleNormValues) <- c("parameter", "min", "max")
maleNormValues <- data.frame(normValues$parameter, normValues$male.min, normValues$male.max)
names(maleNormValues) <- c("parameter", "min", "max")
femaleNormValuesCol <- c()
maleNormValuesCol <- c()
for (i in 1:nrow(normValues)) {
  femaleNormValuesCol <- c(femaleNormValuesCol, paste(as.character(normValues[i, "female.min"]), "-",
                                                      as.character(normValues[i, "female.max"]),
                                                      as.character(normValues[i, "unit"])))
  maleNormValuesCol <- c(maleNormValuesCol, paste(as.character(normValues[i, "male.min"]), "-",
                                                  as.character(normValues[i, "male.max"]),
                                                  as.character(normValues[i, "unit"])))
}
```

Lab Results
=======================================================================
```{r}
# prepare patient selection with helper vector:
# - selectInput takes a named vector to display names coded with an id:
#   See: http://shiny.rstudio.com/reference/shiny/latest/selectInput.html
#   and: https://www.dummies.com/programming/r/how-to-name-the-values-in-your-vectors-in-r/
patData <- patData[order(patData$name), ]
patSelectors <- patData$patientId
names(patSelectors) <- paste(as.character(patData$name),
                             ", ",
                             as.character(patData$firstName),
                             "(",
                             as.character(patData$sex),
                             ") age:",
                             as.character(patData$age))

selectInput("patId", 
            label = "Select Patient:",
            choices = patSelectors)

```

```{r}
# "prettify" data for output
combinedData$date <- as_datetime(combinedData$date, 
                                 origin = lubridate::origin, 
                                 tz = "UTC") # convert int to unixTs-obj using lubridate
combinedData$date <- format(combinedData$date, 
                            format = "%y-%m-%d %H:%M") # convert unixTs to human readable string
# round to reasonable values (using dplyr)
combinedData <- mutate_at(combinedData, vars(na, k, krea, hst), funs(round(., 2)))
combinedData <- mutate_at(combinedData, vars(gfr, hgb, inr, rbc, wbc), funs(round(., 1)))
combinedData <- mutate_at(combinedData, vars(gfr, plt, ptt), funs(round(., 0)))

# build a reactive component for DT
displayData <- reactive({ 
  displayData <- combinedData[combinedData$patientId == input$patId, ] # select by patientId
  displayData <- displayData[order(displayData$date, decreasing = TRUE), ] # sort by date
  rownames(displayData) <- displayData$date # set date as rowname (can't be done earlier, because of likely duplicates)
  displayData <- subset(displayData, select = c(na, k, krea, hst, gfr, hgb, rbc, plt, wbc, inr, ptt)) # select values (if not done here normValues will be wrong!)
  
  # Bind gender-specific normValues to table
  if (patData[patData$patientId == input$patId, "sex"] == "f") {
    displayData <- rbind(femaleNormValuesCol, displayData) # human readable
    displayData <- rbind(displayData, femaleNormValues$min) # to be hidden later
    displayData <- rbind(displayData, femaleNormValues$max)
  } else {
    displayData <- rbind(maleNormValuesCol, displayData)
    displayData <- rbind(displayData, maleNormValues$min)
    displayData <- rbind(displayData, maleNormValues$max)
  }
  rownames(displayData) <- c("norm", rownames(displayData)[-1]) # replace default rowname
  
  displayData <- t(displayData) # transpose table (in order to get that sweet "Kummulativbericht-feeling")
})
```

```{r}
# render DT output
DTOutput(outputId = "resultTable")
output$resultTable <- DT::renderDataTable( # see: https://rstudio.github.io/DT/options.html
  DT::datatable( # using a seperate datatable-obj. to enable formatStyle
    data = displayData(),
    class = "hover nowrap cell-border compact", # https://github.com/rstudio/DT/issues/353, https://datatables.net/manual/styling/classes
    extensions = c("FixedColumns"),
    selection = list(mode = "single", target = "row"), # https://rstudio.github.io/DT/shiny.html
    options = list(initComplete = JS(
                     "function(settings, json) {",
                       "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});",
                     "}"
                   ),
                   ordering = FALSE, # ordering makes no sense in a transposed table
                   paging = FALSE, # display all avail rows on one site (no problem since table is transposed)
                   searching = FALSE, # disable searchbar
                   bInfo = FALSE, # disable "Showing .. of .. Values"
                   scrollY = TRUE,
                   scrollX = TRUE, # enable horizontal scolling
                   fixedColumns = list(leftColumns = 2), # fix columns (rownames + normValuesCol)
                   autoWidth = TRUE, # (https://github.com/rstudio/DT/issues/29#issuecomment-85222039)
                   
                   # Display high/low cell styling
                   columnDefs = list(list(visible = FALSE, targets = c(-2, -1))), # hide last two columns (normVals specific for gender)
                   rowCallback = JS( # implement rowCallback to style single rows. See: docs/write_along.Rmd
                     "function(row, data) {",
                       "for (var i = 2; i < (data.length - 2); i++) {",
                         "if (parseFloat(data[i]) < parseFloat(data[(data.length - 2)])) {",
                           "$('td:eq(' + i + ')', row).html(data[i] + ' -');",
                           "$('td:eq(' + i + ')', row).css('background-color', '#e6f2ff');",
                         "} else if (parseFloat(data[i]) > parseFloat(data[(data.length - 1)])) {",
                           "$('td:eq(' + i + ')', row).html(data[i] + ' +');",
                           "$('td:eq(' + i + ')', row).css('background-color', '#ffebe6');",
                         "}",
                       "}",
                     "}"
                   )
    ),
    callback = JS("table.draw()") # not strictly nessesary but speeds up drawing on data-change (i.e. switching of patients)
  ) 
  # style Columns
  %>% formatStyle(0, backgroundColor = "lightgrey", fontWeight = "bold", pointerEvents = "none") # see write_along.Rmd regarding pointerEvents = "none"
  %>% formatStyle("norm", backgroundColor = "lightgrey", fontSize = "xx-small", pointerEvents = "none")
)
```

Column
-----------------------------------------------------------------------
&nbsp;

```{r}
#Plot Output
plotlyOutput("coursePlot")
output$coursePlot <- renderPlotly(
  if (is.null(input$resultTable_rows_selected)) {
    p <- ggplot() + geom_blank()
    ggplotly(p) %>%
      config(displayModeBar = FALSE,
             scrollZoom = FALSE,
             editable = FALSE) 
  } else {
    # helper function to turn data around (https://groups.google.com/forum/#!topic/ggplot2/qrcvqy6TdzI)
    c_trans <- function(a, b, breaks = b$breaks, format = b$format) {
      a <- as.trans(a)
      b <- as.trans(b)
      name <- paste(a$name, b$name, sep = "-")
      trans <- function(x) a$trans(b$trans(x))
      inv <- function(x) b$inverse(a$inverse(x))
      trans_new(name, trans, inv, breaks = breaks, format = format)
    }
    rev_date <- c_trans("reverse", "time")
    
    data <- data.frame(Date = as.POSIXct(ymd_hm(colnames(displayData())[2:(length(colnames(displayData()))-2)])),
                       Value = as.numeric(as.character(displayData()[input$resultTable_rows_selected, 2:(length(colnames(displayData()))-2)])),
                       row.names = NULL)
    p <- ggplot(data, aes(Date, Value)) + 
      geom_ribbon(aes(ymin = as.numeric(as.character(displayData()[input$resultTable_rows_selected, ][length(colnames(displayData()))-1])),
                      ymax = as.numeric(as.character(displayData()[input$resultTable_rows_selected, ][length(colnames(displayData()))]))),
                  fill = "#98FB98") +
      geom_point(size = 2) +
      geom_path() +
      scale_x_continuous(trans = rev_date)
    
    ggplotly(p, tooltip = c("x", "y")) %>%
      config(displayModeBar = FALSE,
             scrollZoom = FALSE,
             editable = FALSE) 
    
  }
) 
```


Column
-----------------------------------------------------------------------
&nbsp;

```{r}
# check for slow bleeding (hbg falling over two consecutive datapoints in the past)
chkSlowBleed <- reactive({
  data <- displayData()["hgb", -1]
  dataVector <- as.numeric(as.character(data))
  dataVector <- dataVector[2:(length(dataVector)-2)] # remove norm values from dataVector 
  
  for (i in seq(1, length(dataVector)-4)) { # -2 norm values - 2 last values
    if (i < 2 && dataVector[i] < dataVector[i+1] && dataVector[i+1] < dataVector[i+2] # hgb has been falling for two times
        ) { 
      return(HTML(paste(
        '<div class="alert alert-warning alert-dismissible" role="alert">',
        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
          '<strong>Warning - drop in Haemoglobin-Concentration!</strong><br>',
          'This patient experienced a drop in hbg between <strong>',
          names(data[i+2]),
          '</strong> and <strong>',
          names(data[i]),
          '</strong>. This could be a sign of occult gastrointestinal bleeding. ',
          'Further information: <a target="_blank" rel="noopener noreferrer" href="https://www.awmf.org/leitlinien/detail/ll/021-028.html">see Guideline</a>',
        '</div>',
        sep = ""
      )))
    }
  }
  return("")
})

renderUI(chkSlowBleed())

# check for Creatinine increase by 3-fold
chkCreaIncrease <- reactive({
  data <- displayData()["krea", -1]
  dataVector <- as.numeric(as.character(data))
  dataVector <- dataVector[2:(length(dataVector)-2)] # remove norm values from dataVector 
  
  if (max(dataVector) > 3*min(dataVector) && which.max(dataVector) != length(dataVector)-2) { # exclude drop
    return(HTML(paste(
        '<div class="alert alert-warning alert-dismissible" role="alert">',
        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
          '<strong>Warning - rise in Creatinine!</strong><br>',
          'This patient experienced a 3-fold rise in Creatinine. ',
          'This is a sign of <strong>acute kidney injury (AKI)</strong> according to the ',
            '<a target="_blank" rel="noopener noreferrer" href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5094385/">RIFLE criteria</a>.<br> ',
            'Further information: see AKI Guideline ',
            '<a target="_blank" rel="noopener noreferrer" href="https://kdigo.org/wp-content/uploads/2016/10/KDIGO-2012-AKI-Guideline-English.pdf">(English)</a> ',
            '<a target="_blank" rel="noopener noreferrer" href="https://link.springer.com/article/10.1007%2Fs11560-013-0752-1">(German)</a>',
        '</div>',
        sep = ""
      )))
  }
  
})

renderUI(chkCreaIncrease())

# check for acute Creatinine increase over 4 mg/dl 
chkCreaOverFour <- reactive({
  data <- displayData()["krea", -1]
  dataVector <- as.numeric(as.character(data))
  dataVector <- dataVector[2:(length(dataVector)-2)] # remove norm values from dataVector 
  
  for (i in seq(1, length(dataVector)-4)) { # -2 norm values - 2 last values
    if (max(dataVector) > 4 && (dataVector[i]-dataVector[i+1] > 0.5 || dataVector[i]-dataVector[i+2] > 0.5)) { 
      # acute Crea increase meaning from one day to the other or in two days
      # to include timelimit use timedifference using as.numeric(as.POSIXct(names(data[i])))-as.numeric(as.POSIXct(names(data[i+2]))),
      return(HTML(paste(
          '<div class="alert alert-warning alert-dismissible" role="alert">',
            '<button type="button" class="close" data-dismiss="alert" aria-label="Close">',
            '<span aria-hidden="true">&times;</span></button>',
            '<strong>Warning - rise in Creatinine!</strong><br>',
            'This patient experienced an acute rise in Creatinine between <strong>',
            names(data[i+2]),
            '</strong> and <strong>',
            names(data[i]),
            '</strong> over 4 mg/dl. <br>',
            'This is a sign of <strong>acute kidney injury (AKI)</strong> according to the ',
            '<a target="_blank" rel="noopener noreferrer" href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5094385/">RIFLE criteria</a>.<br> ',
            'Further information: see AKI Guideline ',
            '<a target="_blank" rel="noopener noreferrer" href="https://kdigo.org/wp-content/uploads/2016/10/KDIGO-2012-AKI-Guideline-English.pdf">(English)</a> ',
            '<a target="_blank" rel="noopener noreferrer" href="https://link.springer.com/article/10.1007%2Fs11560-013-0752-1">(German)</a>',
          '</div>',
        sep = ""
      )))
  }
}
})

renderUI(chkCreaOverFour())

# check for GFR drop >75%
chkGFRdrop <- reactive({
  data <- displayData()["gfr", -1]
  dataVector <- as.numeric(as.character(data))
  dataVector <- dataVector[2:(length(dataVector)-2)] # remove norm values from dataVector 
  
  if (min(dataVector) < 0.25*max(dataVector) && which.min(dataVector) != length(dataVector)-2) { # exclude rise
    return(HTML(paste(
        '<div class="alert alert-warning alert-dismissible" role="alert">',
        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
          '<strong>Warning - drop in GFR!</strong><br>',
          'This patient experienced a >75% drop in Glomerular Filtration Rate. ',
          'This is a sign of <strong>acute kidney injury (AKI)</strong> according to the ',
          '<a target="_blank" rel="noopener noreferrer" href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5094385/">RIFLE criteria</a>.<br> ',
          'Further information: see AKI Guideline ',
          '<a target="_blank" rel="noopener noreferrer" href="https://kdigo.org/wp-content/uploads/2016/10/KDIGO-2012-AKI-Guideline-English.pdf">(English)</a> ',
          '<a target="_blank" rel="noopener noreferrer" href="https://link.springer.com/article/10.1007%2Fs11560-013-0752-1">(German)</a>',
        '</div>',
        sep = ""
      )))
  }
  
})

renderUI(chkGFRdrop())

# check for HIT probability
chkHITprob <- reactive({
  data <- displayData()["plt", -1]
  dataVector <- as.numeric(as.character(data))
  dataVector <- dataVector[2:(length(dataVector)-2)] # remove norm values from dataVector 
  HITscore <- 0
    if(((max(dataVector) - min(dataVector) <= 0.5*max(dataVector) && (max(dataVector) - min(dataVector) > 0.3*max(dataVector)) || (min(dataVector) > 10 && min(dataVector) < 19)))) {
    HITscore <- HITscore+1
  }
  
  if((max(dataVector) - min(dataVector) > 0.5*max(dataVector)) || (min(dataVector) > 20 && min(dataVector) < 100)) {
    HITscore <- HITscore+2
  }
  
  if(HITscore == 1) {
    return(HTML(paste(
        '<div class="alert alert-warning alert-dismissible" role="alert">',
        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
          '<strong>Warning - Patient\'s platelet levels dropped!</strong><br>',
          'Heparin-induced thrombocytopenia (HIT)-probability: <strong>Moderate</strong>.<br>',
          'Further information: <a target="_blank" rel="noopener noreferrer" href="http://circ.ahajournals.org/content/110/18/e454.full">4-T scoring system</a>',
        '</div>',
        sep = ""
      )))
  }
  
  if(HITscore == 2) {
    return(HTML(paste(
        '<div class="alert alert-warning alert-dismissible" role="alert">',
        '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
          '<strong>Warning - Patient\'s platelet levels dropped!</strong><br>',
          'Heparin-induced thrombocytopenia (HIT)-probability: <strong>High</strong>.<br>',
          'Further information: <a target="_blank" rel="noopener noreferrer" href="http://circ.ahajournals.org/content/110/18/e454.full">4-T scoring system</a>',
        '</div>',
        sep = ""
      )))
  }
})

renderUI(chkHITprob())
```


User Manual
=======================================================================

```{r, echo=FALSE}
htmltools::includeHTML("manual.htm")
```
